name: Fullstack CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./grocery-spring
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring-backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./grocery-angular
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/angular-frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spring-backend:latest
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/angular-frontend:latest
            sudo docker-compose down
            sudo docker-compose up -d --remove-orphans

