name: Fullstack CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./grocery-spring
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring-backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./grocery-angular
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/angular-frontend:latest

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./docker-compose.yml"
          target: "/home/${{ secrets.EC2_USER }}/"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to deployment folder
            cd /home/${{ secrets.EC2_USER }}

            # Install Docker if not installed
            if ! command -v docker &> /dev/null
            then
              echo "Docker not found. Installing Docker..."
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker $USER
            fi

            # Install Docker Compose if not installed
            if ! command -v docker-compose &> /dev/null
            then
              echo "Docker Compose not found. Installing Docker Compose..."
              DOCKER_COMPOSE_VERSION="2.20.2"
              sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            echo "Environment ready"

            # Pull latest images and deploy
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spring-backend:latest
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/angular-frontend:latest
            sudo docker-compose down
            sudo docker-compose up -d --remove-orphans
